Add support for `customer_groups` resource
MedShift/bigc pull request #12
Opened 2022-06-21 20:06 UTC by maxheyn

https://developer.bigcommerce.com/api-reference/9bd6421f356c4-get-all-customer-groups

```py
bigc = BigCommerceCustomerGroupsAPI('store_hash', 'access_token')
res_all = list(bigc.all())
res_get = list(bigc.get(4))
res_create = bigc.create(name='MEDS')
res_update = bigc.update(customer_group_id=13, data={'name':'MedShift'})
res_del = bigc.delete(13)
```

<img width="1243" alt="Screen Shot 2022-06-21 at 4 05 49 PM" src="https://user-images.githubusercontent.com/16215993/174888129-689ae5a1-8c89-4ea8-ae90-9e0a99490690.png">

2022-06-21 20:13 UTC, maxheyn commented
Oops, put get in a list in the example.
`res_get = bigc.get(7)` = `{'id': 7, 'name': 'Entry Level 4', 'category_access': {'type': 'all'}, 'discount_rules': [{'type': 'category', 'category_id': '38', 'method': 'percent', 'amount': '30.0000'}, {'type': 'category', 'category_id': '39', 'method': 'percent', 'amount': '30.0000'}], 'is_group_for_guests': False, 'is_default': False}`

2022-06-21 20:23 UTC, dhartle4 requested changes

2022-06-21 20:23 UTC, dhartle4 commented on bigc/resources/customer_groups.py
> +            'name': name,
My only suggestion here would be to collect extra kwargs like 

https://github.com/MedShift/bigc/blob/master/bigc/resources/customers.py#L46

```suggestion
            'name': name,
            **kwargs
```

2022-06-21 20:55 UTC, dhartle4 approved these changes

2022-06-22 13:24 UTC, r-thomson approved these changes

2022-06-22 13:25 UTC, merged