Add update to customers resource
MedShift/bigc pull request #14
Opened 2022-06-23 19:06 UTC by maxheyn

Adds update() to customers resource

2022-06-23 19:07 UTC, maxheyn commented on bigc/resources/customers.py
> +    def update(self, customer_group_id: int, data: dict) -> dict:
```suggestion
    def update(self, customer_id: int, data: dict) -> dict:
```

2022-06-23 19:07 UTC, maxheyn commented on bigc/resources/customers.py
> +        return self._v3_client.request('PUT', f'/customer/{customer_group_id}', json=data)
```suggestion
        return self._v3_client.request('PUT', f'/customer/{customer_id}', json=data)
```

2022-06-23 19:07 UTC, maxheyn commented on bigc/resources/customers.py
> +        return self._v3_client.request('PUT', f'/customer/{customer_id}', json=data)
```suggestion
        return self._v3_client.request('PUT', f'/customers/{customer_id}', json=data)
```

2022-06-23 20:07 UTC, r-thomson commented on bigc/resources/customers.py
> +        return self._v3_client.request('PUT', f'/customers/{customer_id}', json=data)
This endpoint doesn't seem to actually exist— the v3 API only has a [bulk update endpoint](https://developer.bigcommerce.com/api-reference/595425896c3ec-update-customers).

2022-06-24 13:35 UTC, r-thomson requested changes

2022-06-24 13:35 UTC, r-thomson commented on bigc/resources/customers.py
> +        return self._v3_client.request('PUT', f'/customers', json={'id': customer_id, **data})[0]
```suggestion
        payload = {
            'id': customer_id,
            **data,
        }
        return self._v3_client.request('PUT', f'/customers', json=[payload])[0]
```

2022-06-24 14:05 UTC, r-thomson approved these changes

2022-06-24 14:05 UTC, merged