Add delete for order shipments
MedShift/bigc pull request #27
Opened 2023-03-13 18:38 UTC by maxheyn

2023-03-13 19:01 UTC, maxheyn commented on bigc/resources/orders.py
> +    def delete_shipment(self, order_id: int, shipment_id: int) -> dict:
```suggestion
    def delete_shipment(self, order_id: int, shipment_id: int) -> None:
```

2023-03-13 19:15 UTC, r-thomson requested changes

2023-03-13 19:15 UTC, r-thomson commented on bigc/resources/orders.py
> +        return self._api.v2.delete(f'/orders/{order_id}/shipments/{shipment_id}')
```suggestion
        self._api.v2.delete(f'/orders/{order_id}/shipments/{shipment_id}')
```

2023-03-14 14:30 UTC, r-thomson approved these changes

2023-03-14 15:15 UTC, Iapetus-11 requested changes
What if we wrapped the perform_create for a shipment in an atomic block and then tried saving the Shipment to our database before creating the shipment in bigcommerce, therefore removing the need for the delete_shipment method.

2023-03-14 19:01 UTC, maxheyn commented
We don't need this anymore but if we ever need this in the future then here it is.

2023-03-14 19:01 UTC, closed without merging