Let all_addresses optionally specify customer
MedShift/bigc pull request #39
Opened 2023-06-28 13:29 UTC by maxheyn

Currently, `customers.all_addresses(...)` is written in a way such that you can only call it for a customer. However, BigCommerce does support retrieving all customer addresses for the store. We want this behavior for a migration so that we can make a single request for addresses, rather than `n = len(customers)` amount of requests.

2023-06-28 13:31 UTC, maxheyn commented on bigc/resources/customers.py
> +    def all_addresses(self, customer_id: int | None = None) -> Iterator[dict]:
https://github.com/MedShift/bigc/pull/39/commits/180509078be82535fd1bde9ff983f095db811d30

2023-06-28 13:38 UTC, Iapetus-11 approved these changes
It looks fine but I would've used `params=...` instead of string interpolation in the url

2023-06-28 13:39 UTC, maxheyn commented
> It looks fine but I would've used `params=...` instead of string interpolation in the url

It was already like that 🌈

2023-06-28 13:40 UTC, Iapetus-11 commented
> > It looks fine but I would've used `params=...` instead of string interpolation in the url
> 
> It was already like that 🌈

🌈 ok

2023-06-28 13:53 UTC, collinpotts approved these changes

2023-06-28 14:49 UTC, r-thomson requested changes
+1 to using `params` so we don't need to repeat the `.get_many`

2023-06-28 15:21 UTC, Iapetus-11 approved these changes

2023-06-28 18:42 UTC, r-thomson approved these changes

2023-06-29 13:15 UTC, CraigRobertWhite approved these changes

2023-06-29 13:16 UTC, merged